version: "3"

services:
  mysql:
    container_name: toros_db
    image: mysql/mysql-server:5.7
    env_file:
      - toros_db/.env
    # Set max_allowed_packet to 256M
    command: --max_allowed_packet=32505856
    ports:
      - "3306:3306"
    volumes:
      - ./toros_db/data:/var/lib/mysql
    networks:
      - toros-web

  toros_frontend:
    build:
      context: "./toros_frontend"
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ./toros_frontend/src:/app/src:delegated
      - ./toros_frontend/public:/app/public:delegated
    ports:
      - 3000:3000
    container_name: toros_frontend
    networks:
      - toros-web
  toros_api:
    container_name: toros_api
    image: toros_api
    build:
      context: ./toros_api
      dockerfile: Dockerfile
    command:
      [
        "uvicorn",
        "toros_web_api.main:app",
        "--port=20002",
        "--host=0.0.0.0",
        "--reload"
      ]
    environment:
      COLUMNS: 164
    tty: true
    ports:
      - "20002:20002"
    env_file:
      - ./toros_api/config/.env
    volumes:
      - ./toros_api/toros_web_api:/toros_web_api
      - ./toros_api/config/config.toml:/config/config.toml
    networks:
      - toros-web

networks:
  toros-web:
