import { useState, useEffect } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Company from '../components/Company'
import styles from '../styles/Home.module.css'
import CompanyType from '../types/CompanyType';

const Home: NextPage = () => {
    const [data, setData] = useState<CompanyType[]>([])

    useEffect(() => {
        fetch(`http://localhost:20002/companies`, {
            headers: {
                'Content-type': 'application/json',
                'Accept': 'application/json'
            }
        })
            .then((response) => {
                console.log(response);
                return response.json();
            }).then(resjson => {
                setData(resjson);
            });
    }, []);
    return (
        <div className={styles.container}>
            <Head>
                <title>Foundamental Challenge</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Foundamental Challenge
                </h1>


                <div className={styles.grid}>
                    {data && data.length > 0 && data.map((company, index) => <Company key={index} company={company} />)}

                </div>
            </main>

        </div>
    )
}

export default Home
